DE_EconomySystem {
 repSupplyCostRules {
  RepSupplyCostRule "{68867ACF70A9B1E5}" {
   supplyCost 25
   repRequired 0.5
  }
  RepSupplyCostRule "{68867AD7CB5E5054}" {
   supplyCost 50
  }
  RepSupplyCostRule "{68867AD7C4004EB0}" {
   repRequired 2
  }
  RepSupplyCostRule "{68867AD7DC9DD182}" {
   supplyCost 150
   repRequired 3
  }
  RepSupplyCostRule "{68867AD7D8773CB3}" {
   supplyCost 250
   repRequired 4
  }
 }
}