DE_EconomySystem {
 repSupplyCostRules {
  RepSupplyCostRule "{68A6538D0124818D}" {
   supplyCost 10
   repRequired 0.25
  }
  RepSupplyCostRule "{68867ACF70A9B1E5}" {
   supplyCost 20
   repRequired 0.5
  }
  RepSupplyCostRule "{68867AD7CB5E5054}" {
   supplyCost 40
  }
  RepSupplyCostRule "{68867AD7C4004EB0}" {
   supplyCost 70
   repRequired 1.5
  }
  RepSupplyCostRule "{68867AD7DC9DD182}" {
   supplyCost 120
   repRequired 2
  }
  RepSupplyCostRule "{68867AD7D8773CB3}" {
   supplyCost 200
   repRequired 2.5
  }
  RepSupplyCostRule "{689002159AE90604}" {
   supplyCost 350
   repRequired 3
  }
  RepSupplyCostRule "{6892D3E3522AE8F4}" {
   supplyCost 500
   repRequired 4
  }
 }
}