SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  DE_EconomySystem "{6702E18C0005DE3F}" : "{F479E4FEDA031062}Configs/Systems/DE_EconomySystem_Default.conf" {
  }
 }
}