SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697826E2AC672}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{610A889108B9E97B}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A88913BAE33AD}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855317C7203C6}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{610A8891366602DC}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A8891394AAEDD}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6898553178E181AE}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{610A8EDF9ACF5030}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A8EDF86211C8A}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68985531774F5C14}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{610A922E2B0330B4}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A922E28BF4302}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6898553173CCBCEE}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{610A88925DFD5CBD}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A8892449948D9}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855310E085487}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{6326E455666A8C8D}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A8892449948D9}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855310BE27901}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{610A88925CAF6C8E}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{610A88924ECAD9B8}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6898553107EB64D1}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{62E6D1566FC08BBF}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62E6D84C0F03D382}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{68985531028F82A0}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
    SCR_EntityCatalogEntry "{62E6D1566A65B1A0}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62E6D84C352A9705}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855311D56EB84}" {
       m_eSlotTypes VEHICLE_SMALL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{62BADD29EC18B4D6}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{62BADD2A33F53E7F}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62BADD2A190FA424}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855351AAD3ABE}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{62BADD2A32D68D83}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62BADD2A1CB4D90A}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{6898553510137434}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{62BADD2A31B82823}" {
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62BADD2A12360F37}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{689855353DD711E2}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}