SCR_EditableEntityCore {
 m_BudgetSettings {
  SCR_EditableEntityCoreBudgetSetting "{68886A61412EC09C}" {
   m_Info SCR_BudgetUIInfo "{68886A615BD1AF80}" {
    Name "Cash"
    Icon "{04CC877B9D9EA4AD}UI/Textures/Editor/ContentBrowser/ContentBrowser_Theme_Commercial.edds"
   }
   m_BudgetType CASH
   m_iMinBudgetCost 0
  }
 }
}