SCR_EditableEntityCore {
 m_BudgetSettings {
  SCR_EditableEntityCoreBudgetSetting "{68886A61412EC09C}" {
   m_Info SCR_BudgetUIInfo "{68886A615BD1AF80}" {
    Name "Cash"
    Icon "{04CC877B9D9EA4AD}UI/Textures/Editor/ContentBrowser/ContentBrowser_Theme_Commercial.edds"
    m_iPriorityOrderUI 111
   }
   m_BudgetType CASH
   m_iMinBudgetCost 0
  }
  SCR_EditableEntityCoreBudgetSetting "{688C90114DDCBC82}" {
   m_Info SCR_BudgetUIInfo "{688C90114DDCBCB1}" {
    Name "Rep"
    Icon "{37204ADEBD67C8A6}UI/Imagesets/Notifications/NotificationIcons.imageset"
    IconSetName "Notification_Squad_Leader"
    m_iPriorityOrderUI 112
   }
   m_BudgetType REP
   m_iMinBudgetCost 0
  }
 }
}