PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{65728196752AB09A}" {
       ComponentSerializers {
        SCR_ResourceComponentSerializer "{6702C1B83F40CCC1}" {
         m_aResourceTypeFilter {
          CASH
         }
        }
       }
      }
      EntityPersistenceConfig "{64ECE6462993EA13}" {
       ComponentSerializers {
        SCR_ResourceComponentSerializer "{6702C1B83AC13FE1}" {
         m_aResourceTypeFilter {
          CASH
         }
        }
       }
      }
     }
    }
    PersistenceConfigGroup AI {
     Configurations {
      EntityPersistenceConfig "{64EACAC5BFDB31EC}" {
       ComponentSerializers {
        DE_TraderComponentSerializer "{6892D3C4E01A4866}" {
        }
       }
      }
     }
    }
   }
  }
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Gameplay {
     Configurations {
      ScriptedStatePersistenceConfig "{670A00237E5B1108}" {
       Collection "{6586D01E488CA578}"
       Serializer DE_EconomySystemSerializer "{670A002365790223}" {
       }
      }
     }
    }
   }
  }
 }
 PersistentStates {
  DE_EconomySystemData "{670A002CE403D2A0}" {
  }
 }
}