SCR_EditorAttributeList {
 m_aAttributes {
  DE_SetCashValueEditorAttribute "{68CA3ED660F3386D}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{68CA3ED67EA63095}" {
    Name "Cash Value"
   }
   m_CategoryConfig "{416C6E9ECC3D231D}Configs/Editor/AttributeCategories/Entity.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{68CA3ED6C983FDC1}" {
    m_sSliderValueFormating "$%1k"
    m_fMax 1000
    m_fStep 0.01
   }
  }
 }
}